### PR TITLE
upgrade kubernetes client version to 4.4.2

### PR DESCRIPTION
**Pull request by matuominen**
### What changes were proposed in this pull request?

Updating kubernetes client version to 4.4.2

### Why are the changes needed?

To include the needed kubernetes libraries to make spark to work in cluster mode.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Manually in own development paas. After the correct libraries it was possible to make the spark to work in cluster in kubernetes cluster.

### CODE REVIEW

**Review by amartika69 — APPROVED** [review]
LGTM

**Review by marthasolarte — COMMENTED** [review]
It looks good for me.

**Review by marthasolarte — APPROVED** [review]
ok

**Comment by esahla** [comment]
lgtm

**Review by esahla — APPROVED** [review]
OK

**Pull request merged**
